apiVersion: networking.k8s.io/v1
# UPDATE API
kind: Ingress
# Ingress is a type of object that can map requests outside the cluster to the appropriate resources inside it
# The older method to do this is through LoadBalancer, but it could connect to only one resource inside cluster\
# Cloud provider, like Google Cloud, use LoadBalancers still
# Note that the ingress sends the request directly to the deployment for performance reasons, rather than to the services that govern networking for these deployments

metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    # REMOVE CLASSNAME ANNOTATION
    nginx.ingress.kubernetes.io/use-regex: 'true'
    # ADD ANNOTATION
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    # ADD ANNOTATION
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - multik8s.software
        - www.multik8s.software
      secretName: multik8s-software
#  ingressClassName: nginx
  # ADD INGRESSCLASSNAME FIELD
  rules:
    - host: multik8s.com
      http:
        paths:
          - path: /?(.*)
            # UPDATE PATH
            pathType: Prefix
            # ADD PATHTYPE
            backend:
              service:
                # UPDATE SERVICE FIELDS
                name: client-cluster-ip-service
                port:
                  number: 3000
          - path: /api/?(.*)
            # UPDATE PATH
            pathType: Prefix
            # ADD PATHTYPE
            backend:
              service:
                # UPDATE SERVICE FIELDS
                name: server-cluster-ip-service
                port:
                  number: 5000

    - host: www.multik8s.com
      http:
        paths:
          - path: /?(.*)
            # UPDATE PATH
            pathType: Prefix
            # ADD PATHTYPE
            backend:
              service:
                # UPDATE SERVICE FIELDS
                name: client-cluster-ip-service
                port:
                  number: 3000
          - path: /api/?(.*)
            # UPDATE PATH
            pathType: Prefix
            # ADD PATHTYPE
            backend:
              service:
                # UPDATE SERVICE FIELDS
                name: server-cluster-ip-service
                port:
                  number: 5000